### PR TITLE
restore PHP 5.3 compatibility

### PR DESCRIPTION
**Pull request by remicollet**
Yes... I know... but 5.3 still minimal required version in composer.json ;)

### CODE REVIEW

**Comment by remicollet** [comment]
With PHP 5.3.3 (RHEL-6)

```
PHPUnit 3.7.34 by Sebastian Bergmann.

Configuration read from /builddir/build/BUILD/Autoload-c764a62ac6e558cb22e7a1ce09f4f9554b385937/phpunit.xml.dist

................................................................. 65 / 81 ( 80%)
................

Time: 289 ms, Memory: 8.50Mb

OK (81 tests, 158 assertions)
```

**Comment by theseer** [comment]
Do you actually have still a use case for 5.3 compatibility?

I'm considering to remove all code for everything below PHP 5.6.
That would also include the 5.2 compat output.

**Comment by remicollet** [comment]
> Do you actually have still a use case for 5.3 compatibility?

I still maintain this package in EPEL-6 (5.3) and EPEL-7 (5.4), as used to generate most of our autoloaders.

BTW, I'm fine if you switch minimal dep to 5.6 for a future version (1.n+1)

In all case, if anything critical happens, will still be possible to release a new 1.24.1, 1.24.2..., or simply maintain a downstream patch for it.

**Comment by remicollet** [comment]
Do you plan to release 1.24.1 with this patch soon ? (else I will simply build 1.24.0 with the patch applied)

**Comment by theseer** [comment]
Already working on it.

**Pull request merged**
